services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'app'
    ports:
      - "3306:3306"
    volumes:
      - 'db:/var/lib/mysql'
    networks:
      - network-app

volumes:
  db:
    driver: local

networks:
  network-app:
    driver: bridge
